//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod prelude ;

pub mod blood_test ;
pub mod document ;
pub mod echocardiography ;
pub mod enroll_group ;
pub mod kawasaki ;
pub mod liver_function ;
pub mod patient ;
pub mod physique ;
pub mod samples ;