//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use rocket::serde::{ Serialize, Deserialize };
use rocket::form::FromForm;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, FromForm)]
#[serde(crate="rocket::serde")]
#[sea_orm(table_name = "patient")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub gender: String,
    pub location: String,
    pub birth: String,
    pub group: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::document::Entity")]
    Document,
    #[sea_orm(
        belongs_to = "super::enroll_group::Entity",
        from = "Column::Group",
        to = "super::enroll_group::Column::Id",
        on_update = "SetNull",
        on_delete = "SetNull"
    )]
    EnrollGroup,
}

impl Related<super::document::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Document.def()
    }
}

impl Related<super::enroll_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnrollGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
