//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11
pub use super::kawasaki::group::Entity as KawasakiGroup;
pub use super::kawasaki::patient::Entity as KawasakiPatient;

pub use super::kawasaki::group::Model as KawasakiGroupModel;
pub use super::kawasaki::patient::Model as KawasakiPatientModel;

pub use super::kawasaki::group::ActiveModel as KawasakiGroupActiveModel;
pub use super::kawasaki::patient::ActiveModel as KawasakiPatientActiveModel;

pub use super::kawasaki::group::Column as KawasakiGroupColumn;
pub use super::kawasaki::patient::Column as KawasakiPatientColumn;