//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "kawasaki_blood_test")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub patient: i32,
    pub date: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub wbc: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub ne: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub ly: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub mo: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rbc: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub plt: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::patient::Entity",
        from = "Column::Patient",
        to = "super::patient::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KawasakiPatient,
}

impl Related<super::patient::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KawasakiPatient.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
