//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kawasaki_samples")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub patient: i32,
    pub date: String,
    pub r#type: String,
    pub label: String,
    pub status: String,
    pub note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::patient::Entity",
        from = "Column::Patient",
        to = "super::patient::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    KawasakiPatient,
}

impl Related<super::patient::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KawasakiPatient.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
